# Generated by Django 3.0.6 on 2020-05-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('icono', models.ImageField(help_text='Resolución optima 50x50 px', max_length=200, upload_to='')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('indice', models.PositiveSmallIntegerField(default=1)),
                ('texto_sms', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nombre SMS')),
            ],
        ),
    ]
